License/User/Controllers/OfferLetterGenerationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace User.Controllers
{
    public class OfferLetterGenerationController : Controller
    {
        // GET: OfferLetterGeneration
        public ActionResult OfferLetterGeneration()
        {
            return View();
        }
    }
}

License/User/Controllers/TempMapController.cs
using OfferLetter.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using OfferLetter.Models;
using MongoDB.Driver.Builders;
using MongoDB.Driver;

namespace OfferLetter.Controllers
{
    public class TempMapController : Controller
    {
        MongoContext _dbContext;
        public TempMapController()
        {
            _dbContext = new MongoContext();
        }
        // GET: TempMap
        public ActionResult Index()
        {
            try
            {
                var TempDetails = _dbContext._database.GetCollection<TempMapModel>("tempmap").FindAll().ToList();
                return View(TempDetails);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: TempMap/Details/5
        public ActionResult Details(string id)
        {
            var ID = Query<TempMapModel>.EQ(p => p.Id, new ObjectId(id));
            var TempDetails = _dbContext._database.GetCollection<TempMapModel>("tempmap").FindOne(ID);
            return View(TempDetails);
        }

        // GET: TempMap/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TempMap/Create
        [HttpPost]
        public ActionResult Create(TempMapModel tempMapModel)
        {
            try
            {
                // TODO: Add insert logic here
                var document = _dbContext._database.GetCollection<BsonDocument>("tempmap");
                var query = Query.And(Query.EQ("name", tempMapModel.Template), Query.EQ("Mappingcolumn", tempMapModel.Mappingcolumn), Query.EQ("Title", tempMapModel.Title));

                var count = document.FindAs<TempMapModel>(query).Count();


                if (count == 0)
                {
                    var result = document.Insert(tempMapModel);
                }
                else
                {
                    TempData["Message"] = "Tempalte ALready Exist";
                    return View(tempMapModel);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                return View();
            }
        }

        // GET: TempMap/Edit/5
        public ActionResult Edit(string id)
        {
            try
            {
                var document = _dbContext._database.GetCollection<TempMapModel>("tempmap");

                var Tempcount = document.FindAs<TempMapModel>(Query.EQ("_id", new ObjectId(id))).Count();

                if (Tempcount > 0)
                {
                    var TempObjectid = Query<TempMapModel>.EQ(p => p.Id, new ObjectId(id));

                    var TempDetail = _dbContext._database.GetCollection<TempMapModel>("tempmap").FindOne(TempObjectid);

                    return View(TempDetail);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // POST: TempMap/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, TempMapModel tempMapModel)
        {
            try
            {
                tempMapModel.Id = new ObjectId(id);
                //Mongo Query  
                var tempObjectid = Query<TempMapModel>.EQ(p => p.Id, new ObjectId(id));
                // Document Collections  
                var collection = _dbContext._database.GetCollection<TempMapModel>("tempmap");
                // Document Update which need Id and Data to Update  
                var result = collection.Update(tempObjectid, Update.Replace(tempMapModel), UpdateFlags.None);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TempMap/Delete/5
        public ActionResult Delete(string id)
        {
            var ID = Query<TempMapModel>.EQ(p => p.Id, new ObjectId(id));
            var TempDetails = _dbContext._database.GetCollection<TempMapModel>("tempmap").FindOne(ID);
            return View(TempDetails);
        }

        // POST: TempMap/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, TempMapModel tempMapModel)
        {
            try
            {
                //Mongo Query  
                var tempObjectid = Query<TempMapModel>.EQ(p => p.Id, new ObjectId(id));
                // Document Collections  
                var collection = _dbContext._database.GetCollection<TempMapModel>("tempmap");
                // Document Delete which need ObjectId to Delete Data   
                var result = collection.Remove(tempObjectid, RemoveFlags.Single);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

License/User/Views/TempMap/Create.cshtml
@model OfferLetter.Models.TempMapModel

@{
    ViewBag.Title = "Create";
}

<style type="text/css">

    textarea {
        height: 200px;
        width: 100%;
    }
</style>
<h2>Offer Letter</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Template Mapping</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Template, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Template, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Template, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mappingcolumn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mappingcolumn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mappingcolumn, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<div style="text-align:end"> @Html.ActionLink("Back To Home", "OfferLetterGeneration", "OfferLetterGeneration")</div>

License/User/Views/TempMap/Delete.cshtml
@model OfferLetter.Models.TempMapModel

@{
    ViewBag.Title = "Delete";
}

<h2>Offer Letter</h2>
<h4>Template Mapping</h4>
<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Template)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Template)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mappingcolumn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mappingcolumn)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
<div style="text-align:end"> @Html.ActionLink("Back To Home", "OfferLetterGeneration", "OfferLetterGeneration")</div>

License/User/Views/TempMap/Details.cshtml
@model OfferLetter.Models.TempMapModel

@{
    ViewBag.Title = "Details";
}

<h2>Offer Letter</h2>

<div>
    <h4>Template Mapping</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Template)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Template)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mappingcolumn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mappingcolumn)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<div style="text-align:end"> @Html.ActionLink("Back To Home", "OfferLetterGeneration", "OfferLetterGeneration")</div>

License/User/Views/TempMap/Edit.cshtml
@model OfferLetter.Models.TempMapModel

@{
    ViewBag.Title = "Edit";
}

<style type="text/css">

    textarea {
        height: 200px;
        width: 100%;
    }
</style>
<h2>Offer Letter</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Template Mapping</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Template, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Template, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Template, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mappingcolumn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mappingcolumn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mappingcolumn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<div style="text-align:end">
    @Html.ActionLink("Back To Home", "OfferLetterGeneration", "OfferLetterGeneration")
</div>

License/User/Views/TempMap/Index.cshtml
@model IEnumerable<OfferLetter.Models.TempMapModel>

@{
    ViewBag.Title = "Index";
}

<h2>Offer Letter</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Template)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mappingcolumn)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="width:10%">
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td style="width:40%">
                @Html.DisplayFor(modelItem => item.Template)
            </td>
            <td style="width:30%">
                @Html.DisplayFor(modelItem => item.Mappingcolumn)
            </td>
            <td  style="width:20%">
                @Html.ActionLink("Edit", "Edit", "TempMap", new { @id = item.Id }, new { @class = "btn btn-default" }) |
                @Html.ActionLink("Details", "Details", "TempMap", new { @id = item.Id }, new { @class = "btn btn-default" }) |
                @Html.ActionLink("Delete", "Delete", "TempMap", new { @id = item.Id }, new { @class = "btn btn-default" }) 
            </td>
        </tr>
    }
</table>

<div style="text-align:end;width:100%"> @Html.ActionLink("Back To Home", "OfferLetterGeneration", "OfferLetterGeneration")</div>