License/User/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace User.Models
{
    public class User
    {
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        public string ErrMsg { get; set; }

    }
}

License/User/Controllers/ConcurrentUserListController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using User.Models;

namespace User.Controllers
{
    public class ConcurrentUserListController : Controller
    {
        // GET: ConcurrentUserList
        
        public ActionResult Concurrent()
        {
            string Root = ConfigurationManager.AppSettings["API_PATH"].ToString();
            string ProductKey = ConfigurationManager.AppSettings["PRODUCT_KEY"].ToString();

            List<LicenseInputModel> lstLicenseInputModel = new List<LicenseInputModel>();
            string basrURI = Root + "GetAllLoggedUser?ProductKey=" + ProductKey;
            WebRequest request = WebRequest.Create(basrURI);
            if (request != null)
            {
                request.Credentials = CredentialCache.DefaultCredentials;
                request.ContentType = "application/json";
                request.Method = "Get";
                WebResponse response = request.GetResponse();
                StreamReader reader = new StreamReader(response.GetResponseStream());
                string str = reader.ReadLine();
                if (str != "[]")
                {
                    JArray t = JArray.Parse(str);
                    lstLicenseInputModel = t.ToObject<List<LicenseInputModel>>();
                }
                
                if (lstLicenseInputModel !=null &&lstLicenseInputModel.Count > 0)
                {
                    return View(lstLicenseInputModel);
                }
               
            }
            return View(lstLicenseInputModel);
        }
    }
}

License/User/Controllers/OfferLetterGenerationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace User.Controllers
{
    public class OfferLetterGenerationController : Controller
    {
        // GET: OfferLetterGeneration
        public ActionResult OfferLetterGeneration()
        {
            return View();
        }
    }
}

License/User/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Newtonsoft.Json.Linq;
using User.Models;

namespace User.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        string Root = ConfigurationManager.AppSettings["API_PATH"].ToString();
        string ProductKey = ConfigurationManager.AppSettings["PRODUCT_KEY"].ToString();
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ActionName("Index")]
        public ActionResult Index_Post(User.Models.User usr)
        {
            if (ModelState.IsValid)
            {
                HttpContext.Session["Username"] = usr.UserName;

                string ipAddr = GetIpAddress();
                string browserDet = GetBrowserDetails();
                string deviceDet = IsMobileDevice(Request.UserAgent) ? "Mobile" : "Computer";

                LicenseInputModel lstUser = new Models.LicenseInputModel()
                {
                    Login_ID = usr.UserName,
                    Password = usr.Password,
                    IPAddress = ipAddr,
                    DeviceType = deviceDet,
                    BrowserInfo = browserDet,
                    Product_Key = ProductKey
                };

                string basrURI = Root + "login";
                WebRequest request = WebRequest.Create(basrURI);
                if (request != null)
                {
                    request.Credentials = CredentialCache.DefaultCredentials;
                    request.ContentType = "application/json";
                    request.Method = "POST";
                    var json = new JavaScriptSerializer().Serialize(lstUser);
                    byte[] data = System.Text.Encoding.ASCII.GetBytes(json);
                    request.ContentLength = data.Length;
                    Stream requestStream = request.GetRequestStream();
                    requestStream.Write(data, 0, data.Length);
                    requestStream.Close();

                    WebResponse response = request.GetResponse();
                    StreamReader reader = new StreamReader(response.GetResponseStream());
                    string str = reader.ReadLine();
                    JObject t = JObject.Parse(str);
                    Response respons = t.ToObject<Response>();
                    if (respons.status_code == "1")
                    {
                        return RedirectToAction("HomePage", "HomePage", lstUser);
                    }
                    else
                    {
                        ModelState.AddModelError("ErrMsg", respons.status_Description.ToString());
                    }
                }
            }
            return View(usr);
        }
        //[HttpPost]
        //public JsonResult AjaxMethod(string response)
        //{
        //    Recaptcha recaptcha = new Recaptcha();
        //    string key = ConfigurationManager.AppSettings["SecretKey"];
        //    string url = "https://www.google.com/recaptcha/api/siteverify?secret=" + key + "&response=" + response;
        //    recaptcha.Response = (new WebClient()).DownloadString(url);
        //    return Json(recaptcha);
        //}
        //public string Home()
        //{
        //    return "Home Page";
        //}


        public ActionResult ViewUsers()
        {
            List<LICENSE_USER> lstUsers = new List<LICENSE_USER>();
            string Root = ConfigurationManager.AppSettings["API_PATH"].ToString();
            string ProductKey = ConfigurationManager.AppSettings["PRODUCT_KEY"].ToString();

            List<LICENSE_USER> lstLicenseInputModel = new List<LICENSE_USER>();
            string basrURI = Root + "GetAllUser?ProductKey=" + ProductKey;
            WebRequest request = WebRequest.Create(basrURI);
            if (request != null)
            {
                request.Credentials = CredentialCache.DefaultCredentials;
                request.ContentType = "application/json";
                request.Method = "Get";
                WebResponse response = request.GetResponse();
                StreamReader reader = new StreamReader(response.GetResponseStream());
                string str = reader.ReadLine();
                if (str != "[]")
                {
                    JArray t = JArray.Parse(str);
                    lstLicenseInputModel = t.ToObject<List<LICENSE_USER>>();
                }

                if (lstLicenseInputModel != null && lstLicenseInputModel.Count > 0)
                {
                    return View(lstLicenseInputModel);
                }
            }
            return View(lstLicenseInputModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post(LICENSE_USER userDetails)
        {
            
                LICENSE_USER lstUser = new Models.LICENSE_USER()
                {
                    LOGIN_ID = userDetails.LOGIN_ID,
                    USER_NAME = userDetails.USER_NAME,
                    PASSWORD = userDetails.PASSWORD,
                    PRODUCT_KEY = ProductKey
                };

                string basrURI = Root + "AddUser";
                WebRequest request = WebRequest.Create(basrURI);
                if (request != null)
                {
                    request.Credentials = CredentialCache.DefaultCredentials;
                    request.ContentType = "application/json";
                    request.Method = "POST";
                    var json = new JavaScriptSerializer().Serialize(lstUser);
                    byte[] data = System.Text.Encoding.ASCII.GetBytes(json);
                    request.ContentLength = data.Length;
                    Stream requestStream = request.GetRequestStream();
                    requestStream.Write(data, 0, data.Length);
                    requestStream.Close();

                    WebResponse response = request.GetResponse();
                    StreamReader reader = new StreamReader(response.GetResponseStream());
                    string str = reader.ReadLine();
                    JObject t = JObject.Parse(str);
                    Response respons = t.ToObject<Response>();
                    if (respons.status_code == "1")
                    {
                        return RedirectToAction("ViewUsers");
                    }
                    else
                    {
                        ViewBag.Message = respons.status_Description.ToString();
                    }
                }
            
            return View();
        }

        [HttpPost]
        public ActionResult DeleteUser(string id)
        {
            // Write delete script
            return RedirectToAction("ViewUsers");
        }
        private string GetIpAddress()
        {
            string ipAddress = this.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
            if (string.IsNullOrEmpty(ipAddress))
            {
                ipAddress = this.Request.ServerVariables["REMOTE_ADDR"];
            }
            //ipAddress = this.Request.UserHostAddress;
            return ipAddress;
        }

        private string GetBrowserDetails()
        {
            string userAgent = string.Empty;

            System.Web.HttpBrowserCapabilitiesBase hbc = HttpContext.Request.Browser;

            userAgent = hbc.Browser + " " + hbc.Version;

            return userAgent;
        }


        private bool IsMobileDevice(string userAgent)
        {
            string[] mobileDevices = new string[] {"iphone","ppc",
                                                      "windows ce","blackberry",
                                                      "opera mini","mobile","palm",
                                                      "portable","opera mobi" };
            userAgent = userAgent.ToLower();
            return mobileDevices.Any(x => userAgent.Contains(x));
        }


    }

    public class Recaptcha
    {
        public string Response { get; set; }
    }
    public class Response
    {
        public string status_code { get; set; } //0 failed 1 success
        public string status_Description { get; set; }
    }

}

License/User/Views/User/Create.cshtml
@model User.Models.LICENSE_USER

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>User</title>
</head>
<body style="background-color:aquamarine">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <div style="font-family:Arial">
        <table width="100%">
            <tr>
                <td width="100%">
                    <h2 style="color:darkblue"><i><b>  User Creation</b></i></h2>
                    <br />
                </td>
            </tr>
            <tr>
                <td width="100%">
                    <table width="100%">
                        <tr>
                            <td width="20%"></td>
                            <td width="60%">

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group">
                                            @Html.HiddenFor(model => model.PRODUCT_KEY, null)
                                            @Html.HiddenFor(model => model.USERID, null)
                                            @Html.HiddenFor(model => model.ACTIVESTATUS, null)
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.USER_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.USER_NAME, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.USER_NAME, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.LOGIN_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.LOGIN_ID, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.LOGIN_ID, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.PASSWORD, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.PasswordFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <h4 class="text-danger">@ViewBag.Message</h4>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Create" class="btn btn-default" />
                                            </div>
                                        </div>
                                    </div>
                                }

                            </td>
                            <td width="20%"></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br />
                </td>
            </tr>
            <tr>
                <td>
                    <div>
                        @Html.ActionLink("Back to List", "ViewUsers")
                    </div>
                    <br />
                </td>
            </tr>
        </table>
    </div>

</body>
</html>

License/User/Views/User/Index.cshtml
@model User.Models.User

@{
    ViewBag.Title = "LogIn";
}

@*<h2>Index</h2>*@

<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }

    .error {
        color: red;
    }
</style>
<body style="background-color:lavender">
</body>


<div style="font-family:Arial">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal" style="margin-left:50px; margin-right:100px; padding-right:100px;padding-left:-50px; background-color:beige">

            <table width="100%">
                <tr>
                    <td width="100%">
                        @*<h4>User</h4>*@
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group" style="padding-left:300px">
                            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group" style="padding-left:300px">
                            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group" style="padding-left:300px">
                            @Html.ValidationMessageFor(model => model.ErrMsg, "", htmlAttributes: new { @class = "text-danger" })
                        </div>
                        <div id="dvCaptcha" style="padding-left:350px">
                            </div>
                            <input type="hidden" id="hfCaptcha" />
                            <span id="rfvCaptcha" class="error" style="display:none">Captcha validation is required.</span>
                            <br />
                        <div class="form-group" style="padding-left:300px">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="LogIn" id="btnSubmit" class="btn btn-default" />
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td align="right" style="font-style:italic;color:brown">
                        @Html.ActionLink("Concurrent User List", "Concurrent", "ConcurrentUserList") |
                        @Html.ActionLink("Offer Letter Generation", "OfferLetterGeneration", "OfferLetterGeneration") |
                        @Html.ActionLink("Users List", "ViewUsers")
                    </td>
                </tr>


            </table>
        </div>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script type="text/javascript" src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
                async defer></script>
                <script type="text/javascript">

                            var onloadCallback = function () {
                                grecaptcha.render('dvCaptcha', {
                                    'sitekey': '6LftViEaAAAAAOUSXKsLNNsQJctGv44nPqjRiCBl',
                                    'callback': function (response) {
                                        $.ajax({
                                            type: "POST",
                                            url: "/User/AjaxMethod",
                                            data: "{response: '" + response + "'}",
                                            contentType: "application/json; charset=utf-8",
                                            dataType: "json",
                                            success: function (r) {
                                                var captchaResponse = jQuery.parseJSON(r.Response);
                                                if (captchaResponse.success) {
                                                    $("#hfCaptcha").val(captchaResponse.success);
                                                    $("#rfvCaptcha").hide();
                                                } else {
                                                    $("#hfCaptcha").val("");
                                                    $("#rfvCaptcha").show();
                                                    var error = captchaResponse["error-codes"][0];
                                                    $("#rfvCaptcha").html("RECaptcha error. " + error);
                                                }
                                            }
                                        });
                                    }
                                });
                            };
                            $(function () {
                                $("#btnSubmit").click(function () {
                                    $("#rfvCaptcha").hide();
                                    if ($("#hfCaptcha").val() == "") {
                                        $("#rfvCaptcha").show();
                                        // return false;
                                    }
                                });
                            });
                    </script>

    }


    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@

License/User/Views/User/ViewUsers.cshtml
@model IEnumerable<User.Models.LICENSE_USER>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewUsers</title>
</head>
<body style="background-color:lavender">

    <div style="font-family:Arial">
        <table width="100%">
            <tr>
                <td width="100%">
                    <h2 style="color:darkblue"><i><b>Users List</b></i></h2>
                    <br />
                </td>
            </tr>
            <tr>
                <td width="100%">
                    <table width="100%">
                        <tr>
                            <td width="30%"></td>
                            <td width="40%">


                                <table class="table" width="100%" style="background-color:aquamarine; border:double">
                                    <tr>
                                        <th hidden="hidden" width="65%">
                                            @Html.DisplayNameFor(model => model.USERID)
                                        </th>
                                        <th width="10%">
                                            @Html.DisplayNameFor(model => model.USER_NAME)
                                        </th>
                                        <th width="10%">
                                            @Html.DisplayNameFor(model => model.LOGIN_ID)
                                        </th>
                                        <th hidden="hidden" width="5%">
                                            @Html.DisplayNameFor(model => model.PASSWORD)
                                        </th>
                                        <th hidden="hidden" width="5%">
                                            @Html.DisplayNameFor(model => model.ACTIVESTATUS)
                                        </th>
                                    </tr>

                                    @foreach (var item in Model)
            {
                                        <tr>
                                            <td hidden="hidden">
                                                @Html.HiddenFor(modelItem => item.USERID)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.USER_NAME)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.LOGIN_ID)
                                            </td>
                                            <td hidden="hidden">
                                                @Html.DisplayFor(modelItem => item.PASSWORD)
                                            </td>
                                            <td hidden="hidden">
                                                @Html.DisplayFor(modelItem => item.ACTIVESTATUS)
                                            </td>
                                        </tr>
                                    }

                                </table>

                            </td>
                            <td width="30%"></td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <br />
                </td>
            </tr>
            <tr>
                <td>


                    <div>
                        @Html.ActionLink("Back to Home", "Index")  |

                        @Html.ActionLink("Create New", "Create")
                    </div>
                    <br />
                </td>
            </tr>
        </table>
    </div>
</body>
</html>